### PR TITLE
Added orthogonalization to TwoVectors w unit tests

### PR DESCRIPTION
**Pull request by bokorn-bdaii**
Updated TwoVector constructor of SO3 to orthogonalize the vectors so a valid rotation is always produced. Also added checks for the number of vectors and unit tests.

### CODE REVIEW

**Review by myeatman-bdai — APPROVED** [review]
I think it would be good to undo all the auto formatting changes, this repo doesn't use the same linting and formatting as the other bdai repos.

**Comment by bokorn-bdaii** [comment]
Shoot, ya those ran automatically. I'll clean those out.

**Comment by bokorn-bdaii** [comment]
Updated and removed the formatting changes

**Review by myeatman-bdai — APPROVED** [review]
Looks good! Imma mash the merge button.

**Pull request merged**
